-- SPDX-License-Identifier: MPL-2.0
-- GENERATED by ZenodoDeposits.render_agda_transitions() from src/transitions.jl.
-- Do not edit: run `julia --project proofs/agda/generate.jl`. The test suite
-- fails if this file differs from the Julia transition table.
{-# OPTIONS --safe --without-K #-}
module ZenodoDeposits.Transitions where

open import Data.List.Base using (List; []; _∷_)
open import Data.Product.Base using (_×_; _,_)

data State : Set where
  empty create-uncertain draft uploaded publish-uncertain published : State

data Action : Set where
  create recover upload publish reconcile : Action

data Outcome : Set where
  ok rejected ambiguous : Outcome

data Event : Set where
  sent-create sent-publish minted : Event

allStates : List State
allStates = empty ∷ create-uncertain ∷ draft ∷ uploaded ∷ publish-uncertain ∷ published ∷ []

allActions : List Action
allActions = create ∷ recover ∷ upload ∷ publish ∷ reconcile ∷ []

allOutcomes : List Outcome
allOutcomes = ok ∷ rejected ∷ ambiguous ∷ []

step : State → Action → Outcome → State × List Event
step empty create ok = draft , sent-create ∷ []
step empty create rejected = empty , []
step empty create ambiguous = create-uncertain , sent-create ∷ []
step create-uncertain recover ok = draft , []
step draft upload ok = uploaded , []
step draft upload rejected = draft , []
step draft reconcile ok = published , minted ∷ []
step draft reconcile rejected = draft , []
step uploaded publish ok = published , sent-publish ∷ minted ∷ []
step uploaded publish rejected = uploaded , []
step uploaded publish ambiguous = publish-uncertain , sent-publish ∷ []
step uploaded reconcile ok = published , minted ∷ []
step uploaded reconcile rejected = uploaded , []
step publish-uncertain reconcile ok = published , minted ∷ []
step publish-uncertain reconcile rejected = publish-uncertain , []
step s _ _ = s , []
