# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
#
# The pure journal state machine. The Journal changes state ONLY through
# `transition`, and `proofs/agda/ZenodoDeposits/Transitions.agda` is generated
# from TRANSITIONS by `render_agda_transitions`, so the Agda proofs are about
# exactly this table. A test fails if the committed Agda file is stale.

"""
States of a deposit journal, in order of progress.

- `:empty` — nothing sent yet.
- `:create_uncertain` — a create request was sent (write-ahead) and its outcome
  is unknown. Only [`recover!`](@ref) with the deposition id leaves it.
- `:draft` — a draft with a reserved DOI exists.
- `:uploaded` — every file is uploaded and verified.
- `:publish_uncertain` — a publish request was sent (write-ahead) and its
  outcome is unknown. Only reconciliation (a `GET`) leaves it.
- `:published` — terminal: the DOI is registered.
"""
const STATES = (:empty, :create_uncertain, :draft, :uploaded, :publish_uncertain, :published)

"""Actions the journal can take. `:reconcile` and `:recover` only read remote state."""
const ACTIONS = (:create, :recover, :upload, :publish, :reconcile)

"""Outcomes of an action: definite success, definite rejection, or unknown (crash, timeout, 5xx)."""
const OUTCOMES = (:ok, :rejected, :ambiguous)

"""Externally visible events: a create or publish request sent, and a DOI observed minted."""
const EVENTS = (:sent_create, :sent_publish, :minted)

"""
    TRANSITIONS

The complete transition table `(state, action, outcome) => (next, events)`.
Any triple not listed is not permitted and leaves the state unchanged with no
events. Definite rejections loop back to the same state so the action can be
retried; ambiguous outcomes of `:create` and `:publish` move to an
`*_uncertain` state from which only reading actions are permitted.
"""
const TRANSITIONS = Dict{NTuple{3,Symbol},Tuple{Symbol,Vector{Symbol}}}(
    (:empty, :create, :ok) => (:draft, [:sent_create]),
    (:empty, :create, :rejected) => (:empty, Symbol[]),
    (:empty, :create, :ambiguous) => (:create_uncertain, [:sent_create]),
    (:create_uncertain, :recover, :ok) => (:draft, Symbol[]),
    (:draft, :upload, :ok) => (:uploaded, Symbol[]),
    (:draft, :upload, :rejected) => (:draft, Symbol[]),
    (:uploaded, :publish, :ok) => (:published, [:sent_publish, :minted]),
    (:uploaded, :publish, :rejected) => (:uploaded, Symbol[]),
    (:uploaded, :publish, :ambiguous) => (:publish_uncertain, [:sent_publish]),
    (:draft, :reconcile, :ok) => (:published, [:minted]),
    (:draft, :reconcile, :rejected) => (:draft, Symbol[]),
    (:uploaded, :reconcile, :ok) => (:published, [:minted]),
    (:uploaded, :reconcile, :rejected) => (:uploaded, Symbol[]),
    (:publish_uncertain, :reconcile, :ok) => (:published, [:minted]),
    (:publish_uncertain, :reconcile, :rejected) => (:publish_uncertain, Symbol[]),
)

"""
    transition(state, action, outcome) -> (next_state, events)

Look up [`TRANSITIONS`](@ref). A triple that is not in the table returns
`(state, Symbol[])`, matching the catch-all clause of the Agda `step`.
"""
transition(state::Symbol, action::Symbol, outcome::Symbol) =
    get(TRANSITIONS, (state, action, outcome), (state, Symbol[]))

"""
    permitted(state, action) -> Bool

Whether the table has any entry for `action` in `state`. The journal checks
this before every remote operation, so eligibility is decided by the table.
"""
permitted(state::Symbol, action::Symbol) = any(k -> k[1] == state && k[2] == action, keys(TRANSITIONS))

"""
    _agda(sym) -> String

The Agda constructor name for a state, action, outcome or event symbol.
"""
_agda(sym::Symbol) = replace(String(sym), "_" => "-")

"""
    render_agda_transitions() -> String

Render `proofs/agda/ZenodoDeposits/Transitions.agda` from [`TRANSITIONS`](@ref):
the data types, one `step` clause per table entry in a fixed order, and a
catch-all clause. Run `julia --project proofs/agda/generate.jl` to rewrite it.
"""
function render_agda_transitions()
    io = IOBuffer()
    println(io, "-- SPDX-License-Identifier: MPL-2.0")
    println(io, "-- GENERATED by ZenodoDeposits.render_agda_transitions() from src/transitions.jl.")
    println(io, "-- Do not edit: run `julia --project proofs/agda/generate.jl`. The test suite")
    println(io, "-- fails if this file differs from the Julia transition table.")
    println(io, "{-# OPTIONS --safe --without-K #-}")
    println(io, "module ZenodoDeposits.Transitions where")
    println(io)
    println(io, "open import Data.List.Base using (List; []; _∷_)")
    println(io, "open import Data.Product.Base using (_×_; _,_)")
    for (name, values) in (("State", STATES), ("Action", ACTIONS), ("Outcome", OUTCOMES), ("Event", EVENTS))
        println(io)
        println(io, "data ", name, " : Set where")
        println(io, "  ", join(map(_agda, values), " "), " : ", name)
    end
    println(io)
    for (name, values) in (("allStates", STATES), ("allActions", ACTIONS), ("allOutcomes", OUTCOMES))
        type = Dict("allStates" => "State", "allActions" => "Action", "allOutcomes" => "Outcome")[name]
        println(io, name, " : List ", type)
        println(io, name, " = ", join(map(_agda, values), " ∷ "), " ∷ []")
        println(io)
    end
    println(io, "step : State → Action → Outcome → State × List Event")
    order(k) = (findfirst(==(k[1]), STATES), findfirst(==(k[2]), ACTIONS), findfirst(==(k[3]), OUTCOMES))
    for key in sort!(collect(keys(TRANSITIONS)); by=order)
        next, events = TRANSITIONS[key]
        evs = isempty(events) ? "[]" : join(map(_agda, events), " ∷ ") * " ∷ []"
        println(io, "step ", join(map(_agda, key), " "), " = ", _agda(next), " , ", evs)
    end
    println(io, "step s _ _ = s , []")
    return String(take!(io))
end
